In [1]:
import numpy as np
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from PattRecClasses.func import compute_pX

In [2]:
data = np.genfromtxt('停走跑走停走跑_标准.csv', delimiter=',', names=True)
x = data['x']
y = data['y']
z = data['z']

In [3]:
x.shape

(3555,)

In [4]:
data_c = np.concatenate((x,y,z), axis=0).reshape(3,-1)
data_c

array([[-0.10405556, -0.18050431, -0.2236205 , ..., -0.92830698,
        -0.27569801,  0.17308322],
       [ 0.0965921 ,  0.13906711,  0.17087811, ...,  1.51993227,
         0.46480728, -0.42217035],
       [ 0.09390169,  0.25356793,  0.39153614, ..., -2.87471489,
        -2.98291925, -2.42874281]])

In [28]:
mc = MarkovChain( np.array( [ 0.75, 0.25, 0] ), np.array( [ [ 0.8, 0.1, 0.1 ], [ 0.1, 0.8, 0.1 ], [0.1,0.1,0.8] ] ) ) 

g1 = GaussD(means=[0,2, 3], cov=np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]))
g2 = GaussD(means=[0, 1, 1], cov=np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]))
g3 = GaussD(means=[-1, 0, 2], cov=np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]))
g = [g1, g2, g3]
h  = HMM(mc, g)

In [31]:
data = np.array( [ [ 0.8, 0.1, 0.1 ], [ 0.1, 0.8, 0.1 ], [0.1,0.1,0.8] ] )
pX = compute_pX(data, g,scale=True)

In [32]:
pX

array([[0.00551656, 0.011109  , 0.02237077],
       [1.        , 1.        , 1.        ],
       [0.10025884, 0.10025884, 0.40656966]])

In [35]:
g1 = GaussD(means=[0,2, 3,1], cov=np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0],[0,0,0,1]]))
g2 = GaussD(means=[0, 1, 1,1], cov=np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0],[0,0,0,1]]))
g3 = GaussD(means=[-1, 0, 2,1], cov=np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0],[0,0,0,1]]))
g = [g1, g2, g3]
h  = HMM(mc, g)
data = np.array( [ [ 0.8, 0.1, 0.1], [ 0.1, 0.8, 0.1 ], [0.1,0.1,0.8], [0.8,0.2,0.1] ] )
pX = compute_pX(data, g,scale=True)

In [36]:
pX

array([[0.00551656, 0.011109  , 0.02237077],
       [1.        , 1.        , 1.        ],
       [0.10025884, 0.10025884, 0.40656966]])