In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt

import numpy as np

In [4]:
q = np.array([0.7, 0.15, 0.15])
A = np.array([     [0.1, 0.2, 0.6,0.1],
     [0.1, 0.1, 0.7,0.1],
     [0.3, 0.2, 0.4,0.1],
    ])
# A = np.array([     [0.1, 0.2, 0.7],
#      [0.1, 0.1, 0.8],
#      [0.3, 0.2, 0.5],
#     ])

In [5]:
MarkovChain(initial_prob=q, transition_prob=A).rand(10)

array([1, 3, 3, 2])

In [78]:
q = np.array([0.7, 0.15, 0.15])
# A = np.array([     [0.1, 0.2, 0.6,0.1],
#      [0.1, 0.1, 0.7,0.1],
#      [0.3, 0.2, 0.4,0.1],
#     ])
A = np.array([     [0.1, 0.2, 0.7],
     [0.1, 0.1, 0.8],
     [0.3, 0.2, 0.5],
    ])

mc = MarkovChain(initial_prob=q, transition_prob=A)

In [ ]:
hmm = HMM(mc=mc, )

In [74]:
DiscreteD(q).dataSize

AttributeError: 'DiscreteD' object has no attribute 'dataSize'

In [73]:
MarkovChain(initial_prob=q, transition_prob=A).rand(10)

array([1, 3, 1, 3, 3, 1, 2, 3, 3, 3])

In [75]:
a = np.zeros([2,2])
a

array([[0., 0.],
       [0., 0.]])