In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from PattRecClasses.func import compute_pX
from matplotlib import pyplot as plt

import numpy as np

In [2]:
# Verification (Finite)
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [0.9, 0.1, 0], [0, 0.9, 0.1] ] ) ) 
g1 = GaussD( means=[0], stdevs=[1] )
g2 = GaussD( means=[3], stdevs=[2] )
observations = np.array([-0.2, 2.6, 1.3])
# observations = np.array([0, 3, 0])
distribution = [g1, g2]
h = HMM(mc, distribution)
pX = compute_pX(observations, distribution, scale=True)
alpha_hat, c = mc.forward(pX)
log_prob = h.logprob(observations)

np.set_printoptions(precision=4)
print('alpha_hat = \n', alpha_hat, '\n\nc = \n', c, '\n\nLog Probability = \n', log_prob)

c = np.array([1, 0.1625, 0.8266, 0.0581])
beta_hat = mc.backward(pX, c)
print('\nbeta_hat = \n', beta_hat)

alpha_hat = 
 [[1.     0.3847 0.4189]
 [0.     0.6153 0.5811]] 

c = 
 [1.     0.1625 0.8266 0.0581] 

Log Probability = 
 -9.187726979475208

beta_hat = 
 [[1.0003 1.0393 0.    ]
 [8.4182 9.3536 2.0822]]


In [3]:
# Verification (Infinite)
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [0.9, 0.1], [0.1, 0.9] ] ) ) 
g1 = GaussD( means=[0], stdevs=[1] )
g2 = GaussD( means=[3], stdevs=[2] )
observations = np.array([-0.2, 2.6, 1.3])
distribution = [g1, g2]
h = HMM(mc, distribution)
pX = compute_pX(observations, distribution)
alpha_hat, c = mc.forward(pX)

np.set_printoptions(precision=4)
print('alpha_hat = \n', alpha_hat, '\n\nc = \n', c)

beta_hat = mc.backward(pX, c)
print('\nbeta_hat = \n', beta_hat)

alpha_hat = 
 [[1.     0.3847 0.4591]
 [0.     0.6153 0.5409]] 

c = 
 [1.     0.1625 0.8881]

beta_hat = 
 [[1.     6.7973 1.126 ]
 [5.2223 5.7501 1.126 ]]


In [6]:
# q = np.array([0.3,0.6,0.1])
# A = np.array([[0.8, 0.1, 0.05,0.05], [0.1, 0.7, 0.1,0.1], [0.5, 0.4, 0.05, 0.05]])  # finite
# mc = MarkovChain(q, A)
# g1 = GaussD(means=np.array([0]), stdevs=np.array([1.0]))
# g2 = GaussD(means=np.array([3]), stdevs=np.array([2.0]))
# g3 = GaussD(means=np.array([-1]), stdevs=np.array([1.0]))
# observations = np.array([-0.2, 2.6, 1.3, 1.5, 3.2 ,6.4])
# distribution = [g1, g2, g3]
# h = HMM(mc, distribution)
# pX = compute_pX(observations, distribution, scale=True)
# alpha_hat, c = mc.forward(pX)
# log_prob = h.logprob(observations)
# beta_hat = mc.backward(pX, c)
# print('\n', beta_hat)


 [[0.9942 1.8253 0.4999 0.2545 0.286  0.7192]
 [5.4359 3.5464 1.7711 1.7576 2.0017 1.4385]
 [3.2284 2.7527 1.1467 1.0062 1.1438 0.7192]]
